#!/bin/bash
# =============================================================================
# restartnotice.sh - Server Reboot Notification Script
# =============================================================================
# 
# DESCRIPTION:
#   This script sends an email notification when a server reboots, making it
#   easy to track unexpected restarts or confirm scheduled maintenance windows.
#   Designed to be triggered by cron's @reboot directive.
#
# AUTHOR:
#   Léon "Avic" Simmons (https://github.com/Avicennasis)
#
# LICENSE:
#   MIT License - See LICENSE file for details.
#
# USAGE:
#   1. Edit the configuration variables below (especially RECIPIENT_EMAIL).
#   2. Make the script executable: chmod +x restartnotice.sh
#   3. Add to crontab with: crontab -e
#   4. Insert the line: @reboot /path/to/restartnotice.sh
#
# REQUIREMENTS:
#   - A working mail transfer agent (MTA) such as Postfix, msmtp, or sendmail.
#   - For Gmail, use an App Password rather than your account password.
#     See: https://support.google.com/accounts/answer/185833
#
# =============================================================================

# -----------------------------------------------------------------------------
# CONFIGURATION
# -----------------------------------------------------------------------------
# The email address that will receive the reboot notification.
# Change this to your preferred email address.
RECIPIENT_EMAIL="USERNAME@gmail.com"

# The subject line for the notification email.
# You can customize this to suit your preferences or monitoring needs.
EMAIL_SUBJECT="System Restart Notification"

# -----------------------------------------------------------------------------
# SYSTEM INFORMATION GATHERING
# -----------------------------------------------------------------------------
# Get the system's hostname for identification in the email.
# This helps distinguish notifications when managing multiple servers.
HOSTNAME=$(hostname)

# Capture the current date and time in a human-readable format.
# Format: YYYY Mon DD HH:MM:SS (e.g., "2026 Jan 03 00:15:30")
TIMESTAMP=$(date '+%Y %b %d %H:%M:%S')

# Get the system's uptime information (time since boot).
# This helps confirm this is a fresh reboot and not a false trigger.
UPTIME=$(uptime -p 2>/dev/null || uptime)

# Retrieve the system's IP address for quick remote access reference.
# Uses 'hostname -I' which returns all IP addresses (works on most Linux distros).
# Falls back to 'N/A' if the command fails.
IP_ADDRESS=$(hostname -I 2>/dev/null | awk '{print $1}')
IP_ADDRESS=${IP_ADDRESS:-"N/A"}

# Get kernel version information for troubleshooting purposes.
# Useful when tracking if a reboot was due to a kernel update.
KERNEL_VERSION=$(uname -r)

# Get the operating system name and version.
# Reads from /etc/os-release if available, otherwise falls back to uname.
if [[ -f /etc/os-release ]]; then
    OS_INFO=$(grep -E "^PRETTY_NAME=" /etc/os-release | cut -d'"' -f2)
else
    OS_INFO=$(uname -o)
fi

# -----------------------------------------------------------------------------
# EMAIL BODY CONSTRUCTION
# -----------------------------------------------------------------------------
# Compose a detailed, informative email body with relevant system information.
# Using a heredoc for clean multi-line formatting.
EMAIL_BODY=$(cat <<EOF
Server Reboot Notification
==========================

Server "${HOSTNAME}" has restarted.

Reboot Details:
---------------
  Timestamp:    ${TIMESTAMP}
  Hostname:     ${HOSTNAME}
  IP Address:   ${IP_ADDRESS}
  Uptime:       ${UPTIME}
  OS:           ${OS_INFO}
  Kernel:       ${KERNEL_VERSION}

This notification was automatically generated by restartnotice.sh
upon system startup. If this restart was unexpected, please
investigate the server logs (/var/log/syslog or journalctl).

---
https://github.com/Avicennasis/restartnotice
EOF
)

# -----------------------------------------------------------------------------
# SEND NOTIFICATION EMAIL
# -----------------------------------------------------------------------------
# Send the email using the 'mail' command (provided by mailutils or similar).
# The -s flag specifies the subject line.
# The email body is piped to the mail command via echo.
echo "${EMAIL_BODY}" | mail -s "${EMAIL_SUBJECT}" "${RECIPIENT_EMAIL}"

# Capture the exit code of the mail command for logging purposes.
MAIL_EXIT_CODE=$?

# -----------------------------------------------------------------------------
# LOGGING
# -----------------------------------------------------------------------------
# Log the notification attempt to syslog for auditing and troubleshooting.
# Uses logger command to send messages to the system log.
if [[ ${MAIL_EXIT_CODE} -eq 0 ]]; then
    logger -t restartnotice "Reboot notification email sent successfully to ${RECIPIENT_EMAIL}"
else
    logger -t restartnotice "Failed to send reboot notification email (exit code: ${MAIL_EXIT_CODE})"
fi

# Exit with the same code as the mail command to indicate success/failure.
exit ${MAIL_EXIT_CODE}
